### ISSUE TITLE
It can not use

### ISSUE THREAD

**Issue by ChenyuHou** [Ochii/cso2-users-service#1]
It can not use
Please write a README.MD to tell us how to use
![BPUX6Z3E_CIHB%_N0130$YN](https://user-images.githubusercontent.com/45506338/55293870-ccef3100-542d-11e9-8e86-eac0fbdb5f60.png)

**Comment by Ochii** [comment]
I'm working on it, I'll update this as soon as possible

**Comment by ChenyuHou** [comment]
If I put it on cso2-master-server 0.8.13
It has a new problem
Hope this information can help you
![FVR_BAD~ 6ZYU74TCF)%W15](https://user-images.githubusercontent.com/45506338/55294047-cfeb2100-542f-11e9-924b-89beb4a87f96.png)
