### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by enesvtn** [Ochii/cso2-users-service#2]
Hello @Ochii 

how and where do we install this file?

**Comment by Ochii** [comment]
https://github.com/Ochii/cso2-master-services/ has the necessary docker scripts to launch the services. I haven't written any instructions for it, though

**Comment by enesvtn** [comment]
Hello @Ochii 

The database DB process no longer exists in this CSO2, and this cso2-users-service does not write or read which file it reads.

**Comment by Ochii** [comment]
You need [Docker](https://docs.docker.com/install/overview/) and (Docker Compose](https://docs.docker.com/compose/)

To start the services, in a terminal, go to the script's directory and enter `docker compose up`.
To stop the services enter `docker compose down`

**Comment by Ochii** [comment]
See the README in [cso2-master-services](https://github.com/Ochii/cso2-master-services/) and if you have troubles installing open an issue there
