### ISSUE TITLE
Status code 400 on /users/session API

### ISSUE THREAD

**Issue by GEEKiDoS** [Ochii/cso2-users-service#3]
![random400](https://user-images.githubusercontent.com/14933408/57966443-84131d80-7984-11e9-8a61-cbc28a3c7698.gif)

Description: 
For the first time, I inputed right password for user "ABC123" to ensure my code is right, 
then I input wrong password few times to trigger this issue. (In some case right password also triggers this)

Detail:
Post with LibCURL
Code: https://github.com/GEEKiDoS/cso2-launcher/blob/modularizated/src/Plugins/Login/Auth.cpp#L177

**Comment by Ochii** [comment]
The error should be 409 (session already exists) instead of 401 (bad credentials).

Be careful when exposing the user service to the internet, I didn't design it to be a public service.

If you do a GET /users you will get every user's information (including the hashed password)

**Comment by GEEKiDoS** [comment]
> The error should be 409 (session already exists) instead of 401 (bad credentials).
> 
> Be careful when exposing the user service to the internet, I didn't design it to be a public service.
> 
> If you do a GET /users you will get every user's information (including the hashed password)

That's not "session already exists", I have comfirmed there's no active sesstion in the service.

**Comment by Ochii** [comment]
> > The error should be 409 (session already exists) instead of 401 (bad credentials).
> > Be careful when exposing the user service to the internet, I didn't design it to be a public service.
> > If you do a GET /users you will get every user's information (including the hashed password)
> 
> That's not "session already exists", I have comfirmed there's no active session in the service.
> 
> And the issue is 400 instead of the 401.
> At the end of GIF, the service responsed 400 instead of 401.

I can't recreate this. I executed these steps:

- Created a session with
`curl --data "username=test&password=123" http://localhost:30100/users/session`

It returned status code 201

- Sent multiple create session requests with bad credentials with 
`curl --data "username=test&password=bad" http://localhost:30100/users/session`

They returned status code 401

Maybe try sending the body as JSON? This is how I do it with cURL:

`curl -X POST \
    -H "Content-Type: application/json" \
    -d '{"username":"test","password":"123"}' \
    http://localhost:30100/users/session`

**Comment by GEEKiDoS** [comment]
> > > The error should be 409 (session already exists) instead of 401 (bad credentials).
> > > Be careful when exposing the user service to the internet, I didn't design it to be a public service.
> > > If you do a GET /users you will get every user's information (including the hashed password)
> > 
> > 
> > That's not "session already exists", I have comfirmed there's no active session in the service.
> > And the issue is 400 instead of the 401.
> > At the end of GIF, the service responsed 400 instead of 401.
> 
> I can't recreate this. I executed these steps:
> 
> * Created a session with
>   `curl --data "username=test&password=123" http://localhost:30100/users/session`
> 
> It returned status code 201
> 
> * Sent multiple create session requests with bad credentials with
>   `curl --data "username=test&password=bad" http://localhost:30100/users/session`
> 
> They returned status code 401
> 
> Maybe try sending the body as JSON? This is how I do it with cURL:
> 
> `curl -X POST \ -H "Content-Type: application/json" \ -d '{"username":"test","password":"123"}' \ http://localhost:30100/users/session`

After few tests looks like using json fixed this issue.
